### ISSUE TITLE
[Version] The roadmap of 1chooo.com

### ISSUE THREAD

**Issue by 1chooo** [1chooo/vcard#306]
# v0

**TODO (STRONGLY EXPECTED):** 

- [ ] update the components to render markdown or mdx
- [ ] design the GitHub button used in portfolio
- [ ] re-design the portfolio list to show GitHub stats
- [ ] update code blocks
- [ ] wrap the components into packages
- [ ] wrap the whole app into the npm package
- [ ] Card Designed Widget
- [ ] support light | dark theme

## v0.9.x

- [x] #1092 

## v0.8.x

- [x] #1017 
- [x] #1057 
- [x] #1059 

## v0.7.x

- [x] #886 
- [x] #887 
- [x] #936 
- [x] #952 

## v0.6.x

- [x] #675
- [x] #682
- [x] #693
- [x] #700
- [x] #735
- [x] #755
- [x] #756
- [x] #870 

## v0.5.x

- [x] #578
- [x] #582
- [x] #593
- [x] #621
- [x] #643
- [x] #659

## v0.4.x

- [x] #505 
- [x] #529
- [x] #541
- [x] #555
- [x] #568
- [x] #574

## v0.3.x

- [x] #409
- [x] #421
- [x] #444
- [x] #467
- [x] #477
- [x] #501

## v0.2.x

- [x] #385
- [x] #361
- [x] #344
- [x] #328
- [x] #312
- [x] #307
- [x] #293
